from __future__ import annotations

import sys
from collections import defaultdict
from pathlib import Path

import vibe

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


OUTPUT_PATH = ROOT / "SUPPORTED_MODELS.md"
GITHUB_HF_BASE = "https://huggingface.co"


def _escape_markdown_cell(value: str) -> str:
    return value.replace("|", r"\|").replace("\n", "<br>")


def _link(label: str, url: str) -> str:
    return f"[{_escape_markdown_cell(label)}]({url})"


def _code(text: str) -> str:
    escaped = text.replace("`", "\\`")
    return f"`{escaped}`"


def _slugify(text: str) -> str:
    """Creates a markdown-compatible anchor slug for headers or model IDs."""
    return text.lower().replace(" ", "-").replace("/", "").replace("(", "").replace(")", "")


def _format_backends(info: vibe.ModelPluginInfo) -> str:
    badges = []
    for backend in info.supported_backends:
        if backend == "pytorch":
            badges.append("![PyTorch](https://img.shields.io/badge/-%23EE4C2C?logo=pytorch&logoColor=white)")
        elif backend == "onnx":
            badges.append("![ONNX](https://img.shields.io/badge/-%23005C99?logo=onnx&logoColor=white)")
        else:
            badges.append(_code(backend.value if hasattr(backend, "value") else str(backend)))
    return " ".join(badges) if badges else "—"


def _format_optional_text(value: str | None) -> str:
    if value is None or not value.strip():
        return "—"
    return _escape_markdown_cell(value.strip())


def _format_model_row(info: vibe.ModelPluginInfo) -> str:
    """Formats a single model's metadata as a row in a streamlined markdown table."""
    if info.default_hf_repo:
        repo_url = f"{GITHUB_HF_BASE}/{info.default_hf_repo}"
        display_name = f"**{_link(info.display_name, repo_url)}**"
    else:
        display_name = f"**{_escape_markdown_cell(info.display_name)}**"

    # Assign an anchor to the model ID so recommended models can link to it directly
    model_id_slug = _slugify(info.model_id)
    model_id = f'<a id="{model_id_slug}"></a>`{info.model_id}`'

    backends = _format_backends(info)

    has_tlt = "TagLevelThresholds" in info.supported_processors
    tlt_val = "✔️" if has_tlt else "—"

    # description = _format_optional_text(info.description)

    columns = [
        display_name,
        model_id,
        backends,
        tlt_val,
        # description,
    ]
    return "| " + " | ".join(columns) + " |"


def build_markdown() -> str:
    infos = [
        info
        for info in vibe.describe_all()
        if info.output_type == "tags" and not info.model_id.startswith("generic-timm")
    ]
    infos.sort(key=lambda info: info.model_id)

    grouped: dict[str, list[vibe.ModelPluginInfo]] = defaultdict(list)
    for info in infos:
        grouped[info.family_name].append(info)

    sorted_families = sorted(grouped.keys())

    lines = [
        "# HyVis - Supported Models",
        "",
        f"This file is generated by [{_code('gen_supported_models.py')}](.github/scripts/gen_supported_models.py).",
        "",
        f"Total models: {len(infos)}.",
        "",
        "The currently supported models are trained with exclusive focus on illustrations and artwork.",
        "Performance will naturally degrade when processing photographic or real-world content, though results may still be usable.",
        "Please open an issue if you know of any models and want HyVis to support them.",
        "",
        "## Table of Contents",
        "",
        "- [Recommended Models](#recommended-models)",
        "  - [Danbooru Taggers](#danbooru-taggers)",
        "  - [e621 Taggers](#e621-taggers)",
        "  - [Hugging Face Gated Repositories (AnimeTimm Models)](#hugging-face-gated-repositories-animetimm-models)",
    ]

    for family_name in sorted_families:
        count = len(grouped[family_name])
        slug = _slugify(family_name)
        lines.append(f"- [{family_name} ({count} models)](#{slug})")

    lines.append("")
    lines.append("---")
    lines.append("")

    # Recommended Models Section
    lines.extend(
        [
            "## Recommended Models",
            "",
            "### Danbooru Taggers",
            "",
            "| Model Name | Model ID | Description |",
            "| :--- | :--- | :--- |",
            f"| **WD Eva02 Large v3** | [{_code('wd-eva02-large-v3')}](#{_slugify('wd-eva02-large-v3')}) | Good ol' reliable. With a bit of emphasis on old though. |",
            f"| **WD SwinV2 v3** | [{_code('wd-swinv2-v3')}](#{_slugify('wd-swinv2-v3')}) | Like WD Eva02 Large v3: Good ol' reliable - but roughly 2x lighter.  |",
            f"| **AnimeTimm CaFormer B36** | [{_code('at-caformer-b36-dbv4-full')}](#{_slugify('at-caformer-b36-dbv4-full')}) | Lightweight option with an updated dataset. A tiny bit heavier than SwinV2 |",
            f"| **AnimeTimm Eva02 Large Patch14 448** | [{_code('at-eva02-large-patch14-448-dbv4-full')}](#{_slugify('at-eva02-large-patch14-448-dbv4-full')}) | As heavy as WD Eva02 Large v3, but with updated data. |",
            f"| **AnimeTimm ConvNeXtV2 Huge** | [{_code('at-convnextv2-huge-dbv4-full')}](#{_slugify('at-convnextv2-huge-dbv4-full')}) | Heaviest + Largest + Latest available model. Requires a minimum of 6GB RAM/VRAM at batch size 1. PyTorch only.|",
            "",
            "> Newer and/or larger models do not automatically guarantee better accuracy.",
            "",
            "### e621 Taggers",
            "",
            "| Model Name | Model ID | Description |",
            "| :--- | :--- | :--- |",
            f"| **Hydra 3.5** | [{_code('hydra-3.5')}](#{_slugify('hydra-3.5')}) | The successor to [JTP-3](#{_slugify('jtp-3')}), the only supported models that output e621 tags, and the latest and possibly best to do so, too. PyTorch only. |",
            "",
            "### Hugging Face Gated Repositories (AnimeTimm Models)",
            "",
            "AnimeTimm (`at-`) models are hosted in gated repositories. For automatic downloading via hyvis (leaving the source empty), you must link a Hugging Face account, accept the repository access prompt, and set your User Access Token to the `HF_TOKEN` environment variable.",
            "",
            "> [!NOTE]",
            "> Requesting access explicitly shares your email address with the repository owner. If you prefer to avoid this, maybe you can find a kind soul who will reupload the model.",
            "",
            "---",
            "",
        ]
    )

    lines.extend(
        [
            "### Legend",
            "",
            "- **Model Name:** Just a human-friendly display name. Click it to go to a model's source HuggingFace repository.",
            "- **Model ID:** Unique identifier to use in HyVis config to select which model to run.",
            "- **Backends:** ![ONNX](https://img.shields.io/badge/-%23005C99?logo=onnx&logoColor=white) = ONNX | ![PyTorch](https://img.shields.io/badge/-%23EE4C2C?logo=pytorch&logoColor=white) = PyTorch",
            "- **TLT (Tag-Level Thresholds):** Indicates support for per-tag thresholds.",
            # "- **Description Column:** WIP, currently not really useful but maybe in the future, or not, open for ideas. My current idea is to replace description with keywords instead",
            "",
        ]
    )

    # Generate Table Sections
    for family_name in sorted_families:
        family_models = sorted(grouped[family_name], key=lambda info: info.display_name.lower() or info.model_id)

        # todo: keep description stuff for now, but maybe itll change in future
        # lines.extend(
        #     [
        #         f"## {family_name}",
        #         "",
        #         "| Model Name | Model ID | Backends | [TLT](#legend) | Description |",
        #         "| :--- | :--- | :--- | :---: | :--- |",
        #     ]
        # )
        lines.extend(
            [
                f"## {family_name}",
                "",
                "| Model Name | Model ID | Backends | [TLT](#legend) |",
                "| :--- | :--- | :--- | :---: |",
            ]
        )

        for info in family_models:
            lines.append(_format_model_row(info))

        lines.extend(["", ""])

    lines.extend(
        [
            "",
            "<details><summary>Experimental/Unsupported</summary>",
            "",
            "It is possible to set `source` in the config to a HuggingFace repo ID, and model_id to: `generic-timm-tags`.",
            "This feature is completely untested and unsupported, but in theory it will allow you to use any model from Huggingface, "
            "so long as it is compatible with the `timm` library, which would handle all the architecture stuff. "
            "This would be useful when attempting to use custom models not directly supported by HyVis and exposed as model ID.",
            "I belive this to be a handy feature and would allow the model support to go with the times without requiring a HyVis update. "
            "If you decide to try it out and encounter issues, please open an issue - "
            "However I cannot promise fixes on this since, at least at the time of writing this, I am not really interested in messing with this.",
            "</details>",
            "",
        ]
    )

    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    OUTPUT_PATH.write_text(build_markdown(), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
