[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "hyvis"
version = "0.13.1"
dependencies = [
    "requests",
    "hydrus-api",
    "vibe @ git+https://github.com/DraconicDragon/vibe@72c461123c590eb485ed5fa2f37b27e79f6084d5",
]

[project.scripts]
hyvis = "hyvis.main:cli"

[tool.hatch.metadata]
allow-direct-references = true
