[hyvis]
log_level = "WARNING"

[hydrus]
api_url = "http://127.0.0.1:45678"
api_key = "api key here"

[[hydrus.file_queries]]
tags = [
    "-rating:general",
    "-rating:sensitive",
    "-rating:questionable",
    "-rating:explicit",
]
tag_service_keys = [] # empty == "all known tags"

[hydrus.output_tag_services]
keys = ["1ffa0013df05b86549f5e9bdf19d1f254fb9527120841f44ebceebe928c7a464"]


# *** Output filter  (global) ***

[output_filter]
prefer_tag_level_thresholds = true
tag_level_threshold_relative_offset = 0.1
default_threshold = 0.4


# *** Output selection ***

output_categories = ["rating"]

[output_filter.max_tags_per_category]
"rating" = 1


# *** Tag prefix mapping ***

[output_filter.tag_prefix_mapping]
"rating" = "rating:"


# *** Models ***

[[inference.models]]
model_id = "at-convnextv2-huge-dbv4-full"
#source = ""
device = "auto"
batch_size = 3
# backend  = "pytorch"   # "pytorch" | "onnx" | "auto"
precision = "fp16" # "fp16" | "bf16" | "fp32" | "auto"


[database]
path = "data/hyvis.db"
