# *** Example Config File ***
# An example config file I used to tag only the top confidence rating tag for the query-ed files

[hydrus]
api_url = "http://127.0.0.1:45869"
api_key = "api key here"

[[hydrus.file_queries]]
tags = [
    "-rating:general",
    "-rating:sensitive",
    "-rating:questionable",
    "-rating:explicit",
]
tag_service_keys = [] # empty == "all known tags"

# [hydrus.preview]
# page_name = "hyvis preview"
# rejected_page_name = "hyvis rejected"

[hydrus.output_tag_services]
keys = ["abcd"]


# *** Output filter  (global) ***

[output_filter]
prefer_tag_level_thresholds = true
tag_level_threshold_relative_offset = 0.1
default_threshold = 0.4


# *** Output selection ***

output_categories = ["rating"]

[output_filter.max_tags_per_category]
"rating" = 1


# *** Tag prefix mapping ***

[output_filter.category_tag_prefix_mapping]
"rating" = "rating:"


# *** Models ***

[[inference.models]]
model_id = "at-caformer-b36-dbv4-full"
device = "auto"
batch_size = 3
precision = "fp16"
